FROM python:3.10-slim
WORKDIR /app
COPY web/requirements_web.txt .
RUN pip install --no-cache-dir -r requirements_web.txt
COPY web/ .
EXPOSE 8501
# Streamlit corre por defecto en el puerto 8501
CMD ["streamlit", "run", "client_app.py", "--server.address=0.0.0.0"]